server {
    listen      80;
    server_name pace-server.kro.kr;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location = /health {
        proxy_pass http://pace-app:8080/health;
        access_log off;
    }

    location / {
        # host: 사용자가 접속한 도메인
        # request_uri: 도메인 뒤의 주소
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;

    # 인증서 파일 경로(Certbot이 만들어준 파일들)
    ssl_certificate     /etc/letsencrypt/live/pace-server.kro.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pace-server.kro.kr/privkey.pem;

    include     /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    server_name pace-server.kro.kr;
    # 내 사이트를 다른 사이트의 <iframe> 안에 넣지 못하게 함
    add_header  X-Frame-Options         "SAMEORIGIN"                      always;
    # 서버가 정해준 파일 형식(Content-Type)을 무조건 따르게 강제
    add_header  X-Content-Type-Options  "nosniff"                         always;
    # 브라우저에 내장된 XSS 필터를 켬
    add_header  X-XSS-Protection        "1; mode=block"                   always;
    add_header  Referrer-Policy         "strict-origin-when-cross-origin" always;
    add_header  Content-Security-Policy "default-src 'self';"             always;

    # 경로 설정
    location / {
        # 리버스 프록시 설정
        proxy_pass http://pace-app:8080;
        # proxy_pass http://host.docker.internal:8080;
        # 클라이언트의 실제 정보를 전달하기 위한 설정
        # Nginx를 거치면 Spring boot 입장에서는 접속자가 'Nginx'로 보이기 때문에 실제 접속자의 정보를 헤더에 담아서 넘겨주어야 함

        # 원래 요청의 호스트 이름(도메인)을 그대로 전달
        proxy_set_header Host $host;

        # 접속자의 실제 ip주소를 전달
        proxy_set_header X-Real-IP $remote_addr;

        # 여러 거점을 거쳐온 경우, 전체 경로의 IP 리스트를 전달
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 원래 요청이 http였는지 https였는지 프로토콜 정보를 전달
        proxy_set_header X-Forwarded-Proto $scheme;

        # 타임아웃 설정(60초)
        proxy_connect_timeout 60s;
        proxy_send_timeout    60s;
        proxy_read_timeout    60s;
    }

    location /health {
        proxy_pass http://pace-app:8080/health;
        # proxy_pass http://host.docker.internal:8080/health;

        # 서버 용량을 위해 로그 끄기
        access_log off;
    }
}